version: '3.8'

services:
  php:
    image: php:7-fpm-alpine
    volumes:
      - ./:/var/www/

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw


