<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Author;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Author $author
     *
     * @return int
     */
    public function getNbArticles($author)
    {
        return $author->getArticles()->count();
    }
}
